Group1(Group1) --> user10(user10);
Group1(Group1) --> user11(user11);
Group1(Group1) --> Group2(Group2);
Group1(Group1) --> Group3(Group3);
Group3(Group3) --> Group4(Group4);
Group3(Group3) --> Group5(Group5);
Group4(Group4) --> user7(user7);
Group4(Group4) --> user8(user8);
Group4(Group4) --> user9(user9);
Group4(Group4) --> Group6(Group6);
Group4(Group4) --> Group7(Group7);
Group6(Group6) --> user19(user19);
Group6(Group6) --> user20(user20);
Group6(Group6) --> Group14(Group14);
Group6(Group6) --> Group15(Group15);
Group15(Group15) --> user12(user12);
Group15(Group15) --> user13(user13);
Group15(Group15) --> user14(user14);
Group2(Group2) --> user10(user10);
Group2(Group2) --> user11(user11);
Group2(Group2) --> Group15(Group15);
Group15(Group15) --> user12(user12);
Group15(Group15) --> user13(user13);
Group15(Group15) --> user14(user14);
